#cloud-config

package_update: true
package_upgrade: true

#Install basic dependencies.
packages:
  - wget
  - curl
  - jq
  - ca-certificates
  - apt-transport-https
  - software-properties-common
  - net-tools
  - gnupg
  - lsb-release
  - zip
  - unzip
  - git

#Create a default user.
users:
  - name: droplet
    gecos: "Default user"
    groups: sudo                  #Add to the sudoers group.
    create_home: true             #Create a home directory for the user.
    home: /home/droplet           #Set the home directory.
    shell: /bin/bash              #Set the default shell.
    lock-passwd: false            #Allow password SSH login.
    sudo: ALL=(ALL) NOPASSWD:ALL  #Allows sudo without password.
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0yZhN25LTmFAQp1wG8UTaK4hydDDwU8LsE8qwiOcJ dev-server-key-1
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFis+UM94A+won/C7Wwh0SknyURmpNJESJbBApPfXQ1z dev-user-key-1
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP04bTVc0JEBIkfaq+qYr95i1cHtQIqfsF2fgZHndUpo ranul@TG-LAP-17

#Run shell commands.
runcmd:
  - apt update  

  #Create a swapfile.
  - |
    if [ ! -f /swapfile ]; then
      fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
    fi

  #Set swappiness.
  - |
    sysctl vm.swappiness=10
    echo 'vm.swappiness=10' >> /etc/sysctl.conf

  #Update the hosts file file private IP addresses and hostnames for the cluster nodes.
  - |
    echo "10.0.1.2 ${droplet_cluster_name}-fe.${domain}" >> /etc/hosts
    echo "10.0.1.3 ${droplet_cluster_name}-be.${domain}" >> /etc/hosts
    echo "10.0.1.4 ${droplet_cluster_name}-db.${domain}" >> /etc/hosts
    echo "10.0.1.5 ${droplet_cluster_name}-od.${domain}" >> /etc/hosts
    echo "10.0.1.6 ${droplet_cluster_name}-mem.${domain}" >> /etc/hosts

  #Install the DigitalOcean monitoring agent.
  - curl -sSL https://repos.insights.digitalocean.com/install.sh | bash

  #Create supporting directories.
  - mkdir /home/repos
  - mkdir /home/scripts
  - mkdir /home/apps
  - mkdir /home/backups

#Reboot the server to apply all changes.
power_state:
  mode: reboot
  message: "Rebooting after installing dependencies."
  timeout: 30

final_message: "Cloud-init script has completed successfully and the server rebooted to apply changes."

